name: Tests
on: [push, pull_request]
jobs:
  test:
    strategy:
      matrix:
        os:
          - ubuntu-latest
#          - macOS-latest  # mac doesn't have docker pre-installed?
    runs-on: ${{ matrix.os }}
    services:
      mysql:
        image: bitnami/etcd:3
        env:
          ALLOW_NONE_AUTHENTICATION: "yes"
        ports:
          - 2379:2379

    steps:
      - name: Checkout
        uses: actions/checkout@master
        with:
          fetch-depth: 0

      - name: Set Up Go
        uses: actions/setup-go@v2
        with:
          go-version: '^1'

      - name: Unit test
        run: go test -v -race -coverprofile=coverage.txt -covermode=atomic ./...

      - name: Integration test
        run: |
          uname -a
          fusermount -V
          go build .
          mkdir mnt
          ./etcdfs
          ./etcdfs mnt &
          ls -al
          timeout 20 sh -c 'until mountpoint mnt; do echo "not started yet"; sleep 3s; done'
          ls -al mnt
          echo content >mnt/aa
          ls -al mnt
          cat mnt/aa | grep content
          stat mnt/aa
          rm mnt/aa
          sudo umount mnt
          git clean -fd # GoReleaser needs a clean workspace

      - name: GoReleaser
        uses: goreleaser/goreleaser-action@v2
        if: startsWith(github.ref, 'refs/tags/') && startsWith(matrix.os, 'ubuntu')
        with:
          version: latest
          args: release --rm-dist
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
